# Change these first
owner: DylanVanAssche # Your GitHub username
repo: status-page # Your Github repository name

# Add your sites here
sites:
  - name: Personal website
    url: https://www.dylanvanassche.be
  - name: Matrix
    url: https://chat.dylanvanassche.be
  - name: Riot
    url: https://riot.dylanvanassche.be
  - name: Radicale
    url: https://caldav.dylanvanassche.be
  - name: Thesis
    url: https://thesis.dylanvanassche.be
  - name: Sailfinder
    url: https://sailfinder.dylanvanassche.be
  - name: Daports
    url: https://repo.dylanvanassche.be
  - name: De Pijl VZW
    url: https://www.de-pijl.be

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.dylanvanassche.be
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://dylanvanassche.be/assets/img/avatar.png
  name: Dylan's status page
  introTitle: "Monitoring my services and websites"
  introMessage: "Updates every 5 minutes, hosted by Github Actions"
  navbar:
    - title: Status
      href: /
    - title: About me
      href: https://dylanvanassche.be
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
